/**
 * \file MessageException.java
 *
 *
 * \brief INFO0010 Projet 1
 * \author Andries Alexandre s196948
 * \version 0.1
 * \date 30/10/2022
 *
 */

 /** Class description :
  *
  * MessageException is used to manage exceptions generated by the program.
  *
  */

public class MessageException extends Exception{
    public MessageException(){
        super();
    }

    public MessageException(String text){
        super(text);
    }
}//end MessageException
